### ISSUE TITLE
Add method to easily set authentication headers

### ISSUE THREAD

**Issue by vincentsels** [MelbourneDeveloper/RestClient.Net#12]
Have you considered moving the plumbing code for at least adding basic auth headers:

```c#
var credentials = Convert.ToBase64String(Encoding.UTF8.GetBytes(username + ":" + password));
_client.Headers.Add("Authorization", "Basic " + credentials);
```

into your library and add easy-to-use methods for your consumer, e.g.:

```c#
_client.UseBasicAuthentication(username, password);
```

**Comment by MelbourneDeveloper** [comment]
@vincentsels I would like to do something along those lines but probably not exactly that. Basic authentication is not so basic. What if it requires a bearer token?

There are issues around headers in general that need to be addressed. You can see it in the difference between put and post. 

I'm open to suggestions at this point but not rushing in to anything.

**Comment by MelbourneDeveloper** [comment]
@vincentsels you were right about this one. Great idea. It's the develop branch and will be released as part of V3 soon.

**Comment by MelbourneDeveloper** [comment]
@vincentsels this has been included in version three which has been released on NuGet. Version three is a complete overhaul.
