### ISSUE TITLE
Snyk.io Automated Vulnerabilities Testing Results

### ISSUE THREAD

**Issue by BlueWings98** [MelbourneDeveloper/RestClient.Net#136]
I ran an automated testing over the security.snyk.io website and these were the results:
## Results from Snyk.io (Vulnerabilities in each detected project)
- **RestClient.Net.Samples.Uno.Droid.csproj .NetFramework Version 8**: High 6, Medium 1
- **RestClient.Net.Samples.Uno.Wasm.csproj netstandard2.0**: High 6, Medium 1
- **RestClient.Net.Samples.UnitTests.csproj net45**: High 5, Medium 1
- **RestClient.Net.UnitTests.csproj net6.0**: High 5, Medium 1
- **RestClient.Net.UnitTests.csproj netcoreapp3.1**: High 5, Medium 1
- **RestClient.Net.UnitTests.csproj net5.0**: High 5, Medium 1
- **RestClient.Net.UnitTests.csproj net7.0**: High 5, Medium 1
- **RestClient.Net.PerformanceTests.csproj netcoreapp3.1**: High 2, Medium 1
- **Code Analysis**: High 1, Low 16
- **RestClient.Net.Samples.csproj netstandard2.0**: High 1
- **RestClient.Net.CoreSample.csproj net6.0**: High 1
- **ApiExamples.csproj netcoreapp3.1**: High 1
- **Other included projects**: None

**Comment by MelbourneDeveloper** [comment]
None of these are in the core libraries that get deployed to NuGet so I'm not worried about them
