### ISSUE TITLE
Request body type not passed to serialization adapter

### ISSUE THREAD

**Issue by Silic0nS0ldier** [MelbourneDeveloper/RestClient.Net#14]
I hit an issue while testing a custom serialization adapter. The adapter uses `System.Xml.Serialization.XmlSerializer` to perform serialization and deserialization, both transformations require the type to be properly processed (so that appropriate XML namespaces can be used, etc). I discovered however that the generic is `object` instead of the specified class, looking at the source this appears to be due to the generic not being passed along to the generic call.

I'll open a PR with some (hopefully) backward compatible changes to address this limitation next chance I get.

**Comment by MelbourneDeveloper** [comment]
@Silic0nS0ldier I've looked at this PR and fixed the compilation issue locally.

It's a bit annoying to deal with an extra type parameter but I think I can see why it's necessary based on this issue description. I will keep looking over it, and also consider other options. But, I think this might be a good change.
