### ISSUE TITLE
Can't get code to compile due to StrongNameKey.pfx

### ISSUE THREAD

**Issue by Tam66662** [MelbourneDeveloper/RestClient.Net#4]
Tried to compile either solution, but it fails on the RestClient.NET project:

Compile error reads:
`
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3325	Cannot import the following key file: StrongNameKey.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_40D0A35928393ABA	RestClient.NET	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	3214	
`

I tried running from a developer command line: "sn -i StrongNameKey.pfx VS_KEY_40D0A35928393ABA

But it asked me for a password.  Not sure how to get around all of this.  Any help would be greatly appreciated.

**Comment by MelbourneDeveloper** [comment]
@tam66662

Ah yes. This is because signing is turned on. I will turn it off. Meantime, just go in to properties and switch off the Sign Assembly checkbox.

**Comment by MelbourneDeveloper** [comment]
@Tam66662 this has been fixed in the **develop** branch. Please check that branch out. You must compile in Debug mode. Compiling in Release mode will cause the error you have experience. This will be rolled in to master at the next release. Please let me know if it fixes your issue.

**Comment by Tam66662** [comment]
@MelbourneDeveloper  That fixed it in the developer branch.  Thanks!
