### ISSUE TITLE
Support for custom headers

### ISSUE THREAD

**Issue by Jalroka** [MelbourneDeveloper/RestClient.Net#55]
There seems to be no support for adding a custom header.  While not common there are some api's that require a custom header along with a corresponding value.

**Comment by Jalroka** [comment]
This should fix it if added to MiscExtensions 
        public static void SetCustomHeader(this IClient restClient, string header, string value)
        {
            if (restClient == null) throw new ArgumentNullException(nameof(restClient));
            if (string.IsNullOrEmpty(header) || string.IsNullOrEmpty(value))
                throw new ValidationException(Messages.HeaderOrValueNull);
            if (!restClient.DefaultRequestHeaders.Contains(header))
            {
                restClient.DefaultRequestHeaders.Add(header, value);
            }
        }

And then to Messages

public const string HeaderOrValueNull = "The Content-Type header or value is null or empty";

**Comment by Jalroka** [comment]
Looks like I found another way to do what I wanted that I missed earlier.

apiclient.DefaultRequestHeaders.Add(apiKeyHeader, apiKey);

**Comment by MelbourneDeveloper** [comment]
@Jalroka thanks for reporting. I'm glad you could the issue. Let me know if there's anything else you need help with.
