### ISSUE TITLE
Want to extent RestClient to Functional API Testing on integration with Specflow

### ISSUE THREAD

**Issue by PrasannaJP** [MelbourneDeveloper/RestClient.Net#58]
Want to extent RestClient to Functional API Testing on integration with Specflow. Am aware of as per best practices base URI should not be changed for RestClient but I have requirement to change base for diffrent API request. Could you please let me know how to acive same

Currently it is blocking me. Could you please help me out

**Comment by MelbourneDeveloper** [comment]
@PrasannaJP Hi. You can just change it. 

The property is here
https://github.com/MelbourneDeveloper/RestClient.Net/blob/7214acb5846e10878b58e4db7cb3f78b0ee27628/RestClient.Net/Client.cs#L71

**Comment by PrasannaJP** [comment]
Thank You veru much! I am using your old Code implemented last year. With that I am initializing restClient like 
 SharedVariables._restClient_api1 = new restclientdotnet.RestClient(new NewtonsoftSerializationAdapter(), new System.Uri(ServiceURI._api1));
            SharedVariables._restClient_microservice = new restclientdotnet.RestClient(new NewtonsoftSerializationAdapter(), new System.Uri(ServiceURI._microservice));
            SharedVariables._restClient_autnhenticate = new restclientdotnet.RestClient(new NewtonsoftSerializationAdapter(), new System.Uri(ServiceURI._authentication));
 and will be assigning session taken in Header for all three client. But when I switch the Client to difrent URI its throwing as UnAuthorized error. Can switch restclient for diffrent URI's?

**Comment by MelbourneDeveloper** [comment]
@PrasannaJP that's because of the underlying HttpClient. If you want to use a different base address, also set the Name of the client to the same as the base address. That means a new HttpClient will be created every time there is a new base url. But this is not the recommended practice.

The recommended practice is to use ClientFactory and use a different name for each base url.

**Comment by PrasannaJP** [comment]
I looked into the unit tests, but I am unable fond refrence code for below 

How to create Client Factory for 5 URI and should be getting Client by name for futher usage(how). below code I am trying in test initalize 
SharedVariables._restClient = new Client(new DefaultAdapter(), baseUri: new Uri(ServiceURI._api1), httpClientFactory: GetClientFactory.GetAPITestFactory(), name: "api1");

Factory is created as below 
public static TestClientFactory GetAPITestFactory()
        {
            TestClientFactory .CreateClient("api1");
            TestClientFactory .CreateClient("api2");
            TestClientFactory .CreateClient("smartserver"); 
            TestClientFactory .CreateClient("upload"); 
            TestClientFactory .CreateClient("microservice"); 
            return TestClientFactory ;
        }

My only requirement is should be creating 5 Client of diffrent URI and once I logged in I should be using Client depending on the URI for API calls

**Comment by MelbourneDeveloper** [comment]
@PrasannaJP just create 5 clients with 5 different names and set the baseurl on each one.

**Comment by PrasannaJP** [comment]
But we cant make static, I have trid but not successfull.
