### ISSUE TITLE
Call modifies headers collection

### ISSUE THREAD

**Issue by MelbourneDeveloper** [MelbourneDeveloper/RestClient.Net#61]
When calling SendAsync with a collection of headers, the call can modify the collection that is sent in. This can cause errors in the subsequent calls. A new collection of headers need to be created and merged with default headers.

**Comment by egarim** [comment]
Something like this still happens there is a bug when you send the headers but it seam to happen only on release, I have been searching like crazy before I post an Issue but the but is still happening 

if you execute the following in release you will get a duplicated key exception in the headers, is there a way to fix this? I can give you a hand and fix it myself if you point me in the right direction 

  var result = await client.PostAsync<DataResult, IDataParameters>(Parameters, resource, Headers);

**Comment by MelbourneDeveloper** [comment]
@egarim ,

Firstly, I haven't confirmed that this is a bug. I have a feeling that this is not an issue anymore. I don't think the code is putting default http headers on the HttpClient. You should use Fiddler to check what headers are being sent to the server.

This is the code that I think is relevant:
https://github.com/MelbourneDeveloper/RestClient.Net/blob/f1c247ac3b51f301fdb07de99b817769d817efcc/src/RestClient.Net/DefaultRequestConverter.cs#L91

Please let me know how you go

**Comment by MelbourneDeveloper** [comment]
@egarim 

> you will get a duplicated key exception in the headers

Do you perhaps have duplicate keys in the headers somehow? Can you send a screenshot and stack trace of the error you see?

**Comment by egarim** [comment]
I will make a reproduction project I have been tracking this bug for 2 weeks

**Comment by MelbourneDeveloper** [comment]
@egarim thankyou! 

I'd you can point me to code that breaks, I will do my best to fix it. 

If you can write a failing unit test, even better.

**Comment by egarim** [comment]
Hi Christian
I have new information on this topic, but I need to create a unit test to prove my theory, so what I found so far is that the error happens when you reuse the headers
for example 

                var Headers = new RequestHeadersCollection();
              

                var result1 = await client.PostAsync<DataResult, IDataParameters>(Parameters, resource, Headers);
                var result2 = await client.PostAsync<DataResult, IDataParameters>(Parameters, resource, Headers);

I use a new instance of headers on each request the problem does not seem to happen, here my question is should headers be reusable or should I create a new instance every time I do a request?

**Comment by MelbourneDeveloper** [comment]
@egarim thanks for the information. I might be able to look at this soon. So, you are saying that this code fails with an exception?

**Comment by egarim** [comment]
@MelbourneDeveloper  a code like that will reproduce the issue, I'm reusing the headers but I really don't know if that's allowed, the exception does not happen if you create a new instance of the headers for each request

**Comment by MelbourneDeveloper** [comment]
This sounds like a bug. If so, it should be easy enough to fix. Thankyou!

**Comment by MelbourneDeveloper** [comment]
@egarim I can recreate the issue. Fix on its way.

**Comment by MelbourneDeveloper** [comment]
@egarim the fix in [this nuget package](https://www.nuget.org/packages/RestClient.NET/4.1.0)

There are also some new unit tests to make sure this bug doesn't creep back, and to make sure that general header management is working correctly.

**Comment by egarim** [comment]
@MelbourneDeveloper  Thanks  Christian

**Comment by MelbourneDeveloper** [comment]
@egarim does this resolve your issue?
