### ISSUE TITLE
Blazor wasm won't compile - needs to be updated to latest blazor version

### ISSUE THREAD

**Issue by intech-paul** [MelbourneDeveloper/RestClient.Net#64]
https://github.com/MelbourneDeveloper/RestClient.Net/tree/master/RestClient.Net.Samples.Blazor

needs to be updated to current blazor versions

**Comment by MelbourneDeveloper** [comment]
@intech-paul thanks for the heads up. Will try to do this soon.

**Comment by MelbourneDeveloper** [comment]
@intech-paul would you do a pull request?

**Comment by MelbourneDeveloper** [comment]
@intech-paul this works fine for me. Could you please post the exact error message?

**Comment by intech-paul** [comment]
The source files have been moved from the original locations I linked above, so can't compare to what I originally posted the issue about. Im not working on blazor at the moment but will look at when I do. Paul

**Comment by MelbourneDeveloper** [comment]
@intech-paul no problem. It definitely does work, but I will upgrade Blazor at some point in the future.
