### ISSUE TITLE
Example to PostQuery to cosmos DB blazor wasm

### ISSUE THREAD

**Issue by intech-paul** [MelbourneDeveloper/RestClient.Net#65]
I am uisng blazor wasm to read data from a cosmos db emulator, and am using the code below to read ok:

`    string replydata;
    static string utc_date = DateTime.UtcNow.ToString("r");
    static readonly string endpoint = "https://localhost:8081";
    static readonly string masterKey = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";
    static readonly Uri baseUri = new Uri(endpoint);

    async Task testGET()
    {
        string databaseId = "TablesDB";
        string collectionId = "demoData";
        bool idBased = true;

        string verb = "GET";
        string resourceType = "docs";
        string resourceLink = string.Format("dbs/{0}/colls/{1}/docs", databaseId, collectionId);
        string resourceId = (idBased) ? string.Format("dbs/{0}/colls/{1}", databaseId, collectionId) : collectionId.ToLowerInvariant();

        string authHeader = GenerateMasterKeyAuthorizationSignature(verb, resourceId, resourceType, masterKey, "master", "1.0");

        try
        {
            var client = new Client(new NewtonsoftSerializationAdapter(), new Uri(baseUri, resourceLink));
            client.DefaultRequestHeaders.Add("x-ms-date", utc_date);
            client.DefaultRequestHeaders.Add("x-ms-version", "2015-08-06");
            client.DefaultRequestHeaders.Add("authorization", authHeader);
            client.DefaultRequestHeaders.Add("x-ms-max-item-count", "5");

            var reply = await client.GetAsync<string>();
            replydata = reply;
        }
        catch (Exception ex)
        {
            replydata = ex.Message;
        }
    }
`
How would I change this to send a sqlquery to the db using a POST ?

**Comment by MelbourneDeveloper** [comment]
@intech-paul that's a very loaded question. Firstly, it's not good practice to send SQL over HTTP. I'd recommend building a GraphQL endpoint and then querying that end point. However, this is how you would do a POST

```cs
var client = new Client(new NewtonsoftSerializationAdapter(), new Uri(baseUri, resourceLink));
client.DefaultRequestHeaders.Add("x-ms-date", utc_date);
client.DefaultRequestHeaders.Add("x-ms-version", "2015-08-06");
client.DefaultRequestHeaders.Add("authorization", authHeader);
client.DefaultRequestHeaders.Add("x-ms-max-item-count", "5");
var response = await client.PostAsync<string, string>("SELECT * FROM SOMETABLE");
```

I've removed the resource because it looks like you are passing that in the Url.

Use Fiddler to make sure the transfer looks correct to you.

**Comment by intech-paul** [comment]
Thank you, I have made those changes, I am getting the same error as my code that uses HttpClient, a header authorization message. It is the same header as the GET, except the verb is changed to POST. I wonder if this is a problem with the azure emulator 2.9.2.

Is there some other DB you know of that I can test the POST against ?

{"code":"Unauthorized","message":"Required Header authorization is missing. Ensure a valid Authorization token is passed., Microsoft.Azure.Documents.Common/2.9.2"}

**Comment by MelbourneDeveloper** [comment]
@intech-paul what authorization header does the API expect?

Use fiddler to check what header is being sent

**Comment by intech-paul** [comment]
I found a powerscript example of a REST POST, and the only difference I found was the addition of a Content-Type, so I have added this and am now getting different errors (I am adding data rather than a query as a test).

`            byte[] messageBytes = System.Text.Encoding.UTF8.GetBytes(System.Text.Json.JsonSerializer.Serialize(myData));
            HttpContent content = new ByteArrayContent(messageBytes);
            content.Headers.Add("Content-Type", "application/json");
            content.Headers.Add("x-ms-documentdb-partitionkey","[\""+myData.dateTime.ToLongDateString()+"\"]");          
           
            var response = await client.PostAsync(uri, content);
            var result = await response.Content.ReadAsStringAsync();`


the error I am getting now is
{"code":"BadRequest","message":"Message: {\"Errors\":[\"**PartitionKey extracted from document doesn't match the one specified in the header****\"]}\r\nActivityId: fbd98f54-9267-4b69-bb1c-9e9d078d8f1e, Request URI: /apps/DocDbApp/services/DocDbServer3/partitions/a4cb494f-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: \r\nRequestStartTime: 2020-05-08T05:51:49.8005379Z, RequestEndTime: 2020-05-08T05:51:49.8015388Z, Number of regions attempted:1\r\nResponseTime: 2020-05-08T05:51:49.8015388Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer3/partitions/a4cb494f-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 278, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 1001, RequestCharge: 1.24, ItemLSN: -1, SessionToken: 278, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Create\r\n, SDK: Microsoft.Azure.Documents.Common/2.9.2"}

but the blazor wasm console error in chrome is still reporting the same authorization error !
{"code":"Unauthorized","message":"Required Header authorization is missing. Ensure a valid Authorization token is passed.\r\nActivityId: 9a747baf-01b4-4613-86b8-40e9a60748e7, Microsoft.Azure.Documents.Common/2.9.2"}

**Comment by MelbourneDeveloper** [comment]
@intech-paul 

> I found was the addition of a Content-Type, so I have added this and am now getting different errors (I am adding data rather than a query as a test).

Yes. You're right. The quickstart guide is missing this line. It adds the json content type. It's usually needed for post.

```cs
client.SetJsonContentTypeHeader();
```

>the error I am getting now is
{"code":"BadRequest","message":"M

RestClient.Net is working exactly as requested. The server is telling you that you have not specified a header correctly.
