### ISSUE TITLE
How to Blazor wsam call api?

### ISSUE THREAD

**Issue by rogers228** [MelbourneDeveloper/RestClient.Net#66]
I created a ASP.NET Core Web API and run it at https://localhost:44303/
than i created a Blazor wsam use RestClient.Net call API, and run it at https://localhost:44318/ , this my code, I don't know why the error occurred?
is different port cause?
and how to in Blazor wsam creat api?
sorry i am Learning Blazor alone。
thank you.

`private string postRuturn;
    private string debug;

    public async Task mypost()
    {
        debug = "debug start";
        var msg = new Message() { Time = "20200507", Questid = 2, Note = "this a test", From = "Rogers" };
        var client = new Client(new NewtonsoftSerializationAdapter(), new Uri("https://localhost:44303/pt/258"));

        try
        {
            msg = await client.PostAsync<Message, Message>(msg); //Error here
            postRuturn = msg.Note;
            debug = "try ok";
        }
        catch
        {
            debug = "catch bug";
        }

        //debug = "ok";

    }`

**Comment by MelbourneDeveloper** [comment]
@rogers228 in the catch block, write the exception to the console, and check the console in your browser
