### ISSUE TITLE
Can not change authorization header on token expiry in a thread-safe manner.

### ISSUE THREAD

**Issue by AartBluestoke** [MelbourneDeveloper/RestClient.Net#74]
on initialization of the client you can add an authentication header by:
                    _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + bearerToken);

works for the first token. 1 hour later, you have to .Clear() the default headers before adding the auth header again. That means that the authentication code then needs to handle all/any other headers added by other parts of the code.

1) we need a specialized auth header which is able to be written.
2) we could have the client hold an auth Func<string> which returns a string when called, which is used to populate this value.

**Comment by MelbourneDeveloper** [comment]
@AartBluestoke this is what the [`sendHttpRequestFunc`](https://github.com/MelbourneDeveloper/RestClient.Net/blob/6a2cbd27a6a2fca395ddb70a7659eed8db134063/src/RestClient.Net/Client.cs#L190) parameter on `Client` for.

I'm just working on a unit test to make sure it fits your scenario.

**Comment by MelbourneDeveloper** [comment]
@AartBluestoke another approach is to implement ['IRequestConverter'](https://github.com/MelbourneDeveloper/RestClient.Net/blob/main/src/RestClient.Net/IRequestConverter.cs) . This contains the method whish rensposible for converting the `Request` in to a `HttpRequestMessage`  . You can then inject implementation in to the `Client`. This is the [default one](https://github.com/MelbourneDeveloper/RestClient.Net/blob/6a2cbd27a6a2fca395ddb70a7659eed8db134063/src/RestClient.Net/DefaultRequestConverter.cs#L16).

**Comment by MelbourneDeveloper** [comment]
@AartBluestoke `IRequestConverter` will be dumped in favor of a delegate in version 5.

**Comment by MelbourneDeveloper** [comment]
@AartBluestoke I believe I have a solution for you. I created a branch and created a class that should manage this. Here is the [class](https://github.com/MelbourneDeveloper/RestClient.Net/blob/86a0f23516a7be54112f7560e410eecf8a8ebb2c/src/RestClient.Net.UnitTests/ManagedTokenSender.cs#L14)

Here is a [unit test](https://github.com/MelbourneDeveloper/RestClient.Net/blob/86a0f23516a7be54112f7560e410eecf8a8ebb2c/src/RestClient.Net.UnitTests/TestManagedTokenSender.cs#L28) for testing thread safety.

[This](https://github.com/MelbourneDeveloper/RestClient.Net/blob/86a0f23516a7be54112f7560e410eecf8a8ebb2c/src/RestClient.Net.UnitTests/TestManagedTokenSender.cs#L35) is where you can inject the logic for refreshing the token.

I'm keen to see if you think the unit test does actually validate the logic.

**Comment by MelbourneDeveloper** [comment]
@AartBluestoke I fixed a performance issue [here](https://github.com/MelbourneDeveloper/RestClient.Net/blob/57748c6530e82c18f456794598f5207b26587d34/src/RestClient.Net.UnitTests/ManagedTokenSender.cs#L59)

**Comment by MelbourneDeveloper** [comment]
Version 5 will have immutable default headers. This will mean that if you want to change the default headers, you will need to use the `With` methods for non-destructive mutation or regenerate the client. If you use IHttpClientFactory dependency injection, the `HttpClient`'s handler should not be disposed. It should be retained so there should be no performance loss.

Another approach could be to send the header on every call instead of the default headers collection.
